license_id: "other-pd-nr"
caveats: "This product has been prepared for operational purposes only, to support humanitarian and development activities in Myanmar.\r\nCopyright © Myanmar Information Management Unit. MIMU products are not for sale and can be used free of charge with attribution. For more information see http://themimu.info/mimu-terms-conditions."
methodology: "Other"
methodology_other: "Indicative only. For detailed mapping and further analysis, please verify data in the field. For any feedback to help us improve dataset accuracy and completeness, please contact maps@themimu.info"
dataset_source: "Myanmar Information Management Unit (MIMU)"
package_creator: "mcarans"
private: False
