# Collector specific configuration
base_url: "https://geonode.themimu.info"
dataset_tags_mapping:
  "mimu-geonode-myanmar-national-boundary-mimu":
    - "administrative boundaries-divisions"
  "mimu-geonode-myanmar-state-and-region-boundaries-mimu":
    - "administrative boundaries-divisions"
  "mimu-geonode-myanmar-state-and-region-boundaries-with-sub-regions-mimu":
    - "administrative boundaries-divisions"
  "mimu-geonode-myanmar-district-boundaries-mimu":
    - "administrative boundaries-divisions"
